export const requests = [
  {
    id: 1,
    printer_id: 1,
    request_date: '2022-6-01',
    maintenance_type: 'Routine Check',
    description: 'Routine maintenance check and toner replacement',
    status: 'Resolved',
    resolved_date: '2022-6-02',
  },
  {
    id: 2,
    printer_id: 2,
    request_date: '2022-6-15',
    maintenance_type: 'Repair',
    description: 'Printer jam and paper feed issue',
    status: 'Pending',
    resolved_date: null,
  },
  {
    id: 13,
    printer_id: 13,
    request_date: '2022-10-10',
    maintenance_type: 'Firmware Update',
    description: 'Update printer firmware to version 1.5.0',
    status: 'Resolved',
    resolved_date: '2022-10-11',
  },
  {
    id: 14,
    printer_id: 14,
    request_date: '2022-10-20',
    maintenance_type: 'Toner Replacement',
    description: 'Replace toner cartridges',
    status: 'Pending',
    resolved_date: null,
  },
  {
    id: 16,
    printer_id: 1,
    request_date: '2024-7-02',
    maintenance_type: 'test',
    description: 'trest',
    status: 'Pending',
    resolved_date: null,
  },
  {
    id: 17,
    printer_id: 1,
    request_date: '2024-7-27',
    maintenance_type: '',
    description: '',
    status: 'Pending',
    resolved_date: null,
  },
  {
    id: 18,
    printer_id: 1,
    request_date: '2024-7-28',
    maintenance_type: '',
    description: '',
    status: 'Pending',
    resolved_date: null,
  },
];
