export const constants = {
    auth: {
        REFRESH_TOKEN: 'REFRESH_TOKEN',
        REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
        REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',
        REGISTER: 'REGISTER',
        REGISTER_SUCCESS: "REGISTER_SUCCESS",
        REGISTER_FAIL: "REGISTER_FAIL",
        LOGIN: 'LOGIN',
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_FAIL: "LOGIN_FAIL",
        LOGOUT: "LOGOUT",
        GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
        GET_USER_DATA_FAIL: 'GET_USER_DATA_FAIL',
    },
    printer: {
        GET_DEPARTMENT_PRINTERS: 'GET_DEPARTMENT_PRINTERS',
        GET_DEPARTMENT_PRINTERS_SUCCESS: 'GET_DEPARTMENT_PRINTERS_SUCCESS',
        GET_DEPARTMENT_PRINTERS_FAILURE: 'GET_DEPARTMENT_PRINTERS_FAILURE',
        GET_ALL_PRINTERS: 'GET_ALL_PRINTERS',
        GET_ALL_PRINTERS_SUCCESS: 'GET_ALL_PRINTERS_SUCCESS',
        GET_ALL_PRINTERS_FAILURE: 'GET_ALL_PRINTERS_FAILURE',
    }, 
    profile: {
        GET_DEPARTMENTS: 'GET_DEPARTMENTS',
        GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
        GET_DEPARTMENTS_FAILURE: 'GET_DEPARTMENTS_FAILURE'
    }
}
