export {default as AddPrinter } from './add-printer'
export {default as DeletePrinter } from './delete-printer'
export {default as EditPrinter } from './edit-printer'
export {default as PrinterDetails } from './printer-details'
export {default as PrinterList } from './printer-list'