export class CONSTANTS {
  static ADMIN = 'ADMIN';
  static USER = 'USER';
  static PURGE = 'PURGE';
  static REFRESH_TOKEN = 'REFRESH_TOKEN';
  static REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
  static REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';
  static REGISTER = 'REGISTER';
  static REGISTER_SUCCESS = 'REGISTER_SUCCESS';
  static REGISTER_FAIL = 'REGISTER_FAIL';
  static LOGIN = 'LOGIN';
  static LOGIN_SUCCESS = 'LOGIN_SUCCESS';
  static LOGIN_FAIL = 'LOGIN_FAIL';
  static LOGOUT = 'LOGOUT';
  static GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
  static GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';
  static GET_DEPARTMENT_PRINTERS = 'GET_DEPARTMENT_PRINTERS';
  static GET_DEPARTMENT_PRINTERS_SUCCESS = 'GET_DEPARTMENT_PRINTERS_SUCCESS';
  static GET_DEPARTMENT_PRINTERS_FAILURE = 'GET_DEPARTMENT_PRINTERS_FAILURE';
  static GET_ALL_PRINTERS = 'GET_ALL_PRINTERS';
  static GET_ALL_PRINTERS_SUCCESS = 'GET_ALL_PRINTERS_SUCCESS';
  static GET_ALL_PRINTERS_FAILURE = 'GET_ALL_PRINTERS_FAILURE';
  static GET_DEPARTMENTS = 'GET_DEPARTMENTS';
  static GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
  static GET_DEPARTMENTS_FAILURE = 'GET_DEPARTMENTS_FAILURE';
  static UPDATE_USER_DATA = 'UPDATE_USER_DATA';
  static UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
  static UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE';
  static CLEAR_PERSIST = 'CLEAR_PERSIST';
  static FIFTEEN_MINUTES = 15 * 60 * 1000;
  static GET_DEPARTMENT_METRICS = 'GET_DEPARTMENT_METRICS';
  static GET_DEPARTMENT_METRICS_SUCCESS = 'GET_DEPARTMENT_METRICS_SUCCESS';
  static GET_DEPARTMENT_METRICS_FAILURE = 'GET_DEPARTMENT_METRICS_FAILURE';
  static GET_DEPARTMENT_BILLING_HISTORY = 'GET_DEPARTMENT_BILLING_HISTORY';
  static GET_DEPARTMENT_BILLING_HISTORY_SUCCESS =
    'GET_DEPARTMENT_BILLING_HISTORY_SUCCESS';
  static GET_DEPARTMENT_BILLING_HISTORY_FAILURE =
    'GET_DEPARTMENT_BILLING_HISTORY_FAILURE';
  static GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
  static GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
  static GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';
  static SELECT_PRINTER = 'SELECT_PRINTER';
  static UPDATE_PRINTER_SUCCESS = 'UPDATE_PRINTER_SUCCESS';
  static UPDATE_PRINTER_FAILURE = 'UPDATE_PRINTER_FAILURE';
  static DELETE_PRINTER_SUCCESS = 'DELETE_PRINTER_SUCCESS';
  static DELETE_PRINTER_FAILURE = 'DELETE_PRINTER_FAILURE';
  static ADD_PRINTER_SUCCESS = 'ADD_PRINTER_SUCCESS';
  static ADD_PRINTER_FAILURE = 'ADD_PRINTER_FAILURE';
  static GET_MAINTENANCE_REQUESTS_SUCCESS = 'GET_MAINTENANCE_REQUESTS_SUCCESS';
  static GET_MAINTENANCE_REQUESTS_FAILURE = 'GET_MAINTENANCE_REQUESTS_FAILURE';
  static ADD_MAINTENANCE_REQUEST_SUCCESS = 'ADD_MAINTENANCE_REQUEST_SUCCESS';
  static ADD_MAINTENANCE_REQUEST_FAILURE = 'ADD_MAINTENANCE_REQUEST_FAILURE';
  static SET_USER_TYPE = 'SET_USER_TYPE';
  static PENDING = 'PENDING';
  static UPDATE_MAINTENANCE_REQUEST_SUCCESS =
    'UPDATE_MAINTENANCE_REQUEST_SUCCESS';
  static UPDATE_MAINTENANCE_REQUEST_FAILURE =
    'UPDATE_MAINTENANCE_REQUEST_FAILURE';
}
