export const constants = {
    auth: {
        INITIALIZE_AUTH: 'INITIALIZE_AUTH',
        INITIALIZE_AUTH_SUCCESS: 'INITIALIZE_AUTH_SUCCESS',
        INITIALIZE_AUTH_FAILURE: 'INITIALIZE_AUTH_FAILURE',
        REGISTER_SUCCESS: "REGISTER_SUCCESS",
        REGISTER_FAIL: "REGISTER_FAIL",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_FAIL: "LOGIN_FAIL",
        LOGOUT: "LOGOUT"
    },
    user: {
        GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
        GET_USER_DATA_FAIL: 'GET_USER_DATA_FAIL',
        CLEAR_USER: 'CLEAR_USER'
    }
}
