export {default as Login} from './login'
export {default as Dashboard} from './dashboard'
export {default as Account} from './account'
export {default as Home} from './home'
export {default as Register} from './register'